FROM python:3.11-slim

WORKDIR /envdocker

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENV dpath=/Users/Owner/OneDrive/Desktop\Scrapyard/Datasets.csv
ENV pswd=Notreally820

EXPOSE 5000
CMD ["python","app.py"]